# Generated by Django 4.2.16 on 2025-02-10 16:30

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.URLField(
                blank=True, null=True, validators=[users.validators.validate_github_url]
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[users.validators.validate_linkedin_url],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[users.validators.validate_twitter_url],
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["users"], name="users_profi_users_i_c7b77d_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["badge"], name="users_profi_badge_f7a79c_idx"),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(fields=["user"], name="users_users_user_id_1ba234_idx"),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["-created_at"], name="users_users_created_0556de_idx"
            ),
        ),
    ]
