# Generated by Django 4.2.16 on 2025-02-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_github_alter_profile_linkedin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Controls whether the badge is displayed",
                verbose_name="Availability Status",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_available"], name="users_profi_is_avai_bf7b4a_idx"
            ),
        ),
    ]
