# Generated by Django 4.2.16 on 2025-02-18 07:29

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_is_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="devto",
            field=models.URLField(
                blank=True, null=True, validators=[users.validators.validate_devto_url]
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[users.validators.validate_facebook_url],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="hackerrank",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[users.validators.validate_hackerrank_url],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="leetcode",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[users.validators.validate_leetcode_url],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="medium",
            field=models.URLField(
                blank=True, null=True, validators=[users.validators.validate_medium_url]
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="portfolio",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[users.validators.validate_portfolio_url],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stackoverflow",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[users.validators.validate_stackoverflow_url],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="youtube",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[users.validators.validate_youtube_url],
            ),
        ),
    ]
