# Generated by Django 4.2.16 on 2025-02-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usersession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersession",
            options={"ordering": ["-last_activity"]},
        ),
        migrations.AddField(
            model_name="usersession",
            name="device_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="expires_at",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersession",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "-last_activity"], name="users_users_user_id_f9f20a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="users_users_session_70af4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_active"], name="users_users_is_acti_8d4729_idx"
            ),
        ),
    ]
