# Generated by Django 4.2.16 on 2025-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("profile_update", "Profile Update"),
                    ("mention", "Mention"),
                    ("system", "System Notification"),
                    ("session_terminated", "Session Terminated"),
                    ("sessions_terminated", "Multiple Sessions Terminated"),
                ],
                help_text="Type of notification",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
